# rubocop:disable Layout/LineLength

[
  { id: 1, name: 'CoronaVac', formal_name: 'Sinovac COVID-19 CoronaVac',
    second_dose_after_in_days: 4 * 7, legacy_name: 'coronavac' },
  { id: 2, name: 'AstraZeneca', formal_name: 'Oxford–AstraZeneca COVID-19 ChAdOx1 (AZD1222)',
    second_dose_after_in_days: 13 * 7, legacy_name: 'astra_zeneca' }
].each do |h|
  Vaccine.find_or_initialize_by(id: h[:id]).tap { |r| r.update!(h) }
end

[
  { id: 23, name: 'Trabalhador(a) da Saúde', parent_group_id: nil, context: 'priority', position: 1 },
  { id: 24, name: 'Trabalhador(a) da Educação', parent_group_id: nil, context: 'priority', position: 2, active: false },
  { id: 25, name: 'Trabalhador(a) das Forças de Seguranças e Salvamento', parent_group_id: nil, context: 'priority', position: 10 },
  { id: 26, name: 'Forças Armadas', parent_group_id: nil, context: 'priority', position: 4 },
  { id: 27, name: 'Portador(a) de comorbidade', parent_group_id: nil, context: 'priority', position: 0, active: false },
  { id: 28, name: 'Trabalhador(a) de transporte coletivo rodoviário de passageiros urbano e de longoprazo', parent_group_id: nil, context: 'priority', position: 5 },
  { id: 29, name: 'Trabalhador(a) de transporte metroviário e ferroviário', parent_group_id: nil, context: 'priority', position: 6 },
  { id: 30, name: 'Trabalhador(a) do transporte aéreo', parent_group_id: nil, context: 'priority', position: 7 },
  { id: 31, name: 'Trabalhador(a) do transporte aquaviário', parent_group_id: nil, context: 'priority', position: 8 },
  { id: 32, name: 'Caminhoneiro(a)', parent_group_id: nil, context: 'priority', position: 9 },
  { id: 33, name: 'Trabalhador(a) portuário', parent_group_id: nil, context: 'priority', position: 10 },
  { id: 34, name: 'Trabalhador(a) da construção civil', parent_group_id: nil, context: 'priority', position: 11 },
  { id: 35, name: 'Pessoa com deficiência', parent_group_id: nil, context: 'priority', position: 3 },
  { id: 36, name: 'Diabetes mellitus', parent_group_id: nil, context: 'comorbidity', position: 1 },
  { id: 37, name: 'Pneumopatias crônicas graves', parent_group_id: nil, context: 'comorbidity', position: 2 },
  { id: 38, name: 'Hipertensão', parent_group_id: nil, context: 'comorbidity', position: 3 },
  { id: 39, name: 'Doenças cardiovasculares (do coração)', parent_group_id: nil, context: 'comorbidity', position: 5 },
  { id: 40, name: 'Doença cerebrovascular', parent_group_id: nil, context: 'comorbidity', position: 6 },
  { id: 41, name: 'Doença renal crônica', parent_group_id: nil, context: 'comorbidity', position: 2 },
  { id: 42, name: 'Imunossuprimidos', parent_group_id: nil, context: 'comorbidity', position: 7 },
  { id: 43, name: 'Anemia falciforme', parent_group_id: nil, context: 'comorbidity', position: 12 },
  { id: 44, name: 'Obesidade mórbida (IMC >=40)', parent_group_id: nil, context: 'comorbidity', position: 13 },
  { id: 45, name: 'Síndrome de down', parent_group_id: nil, context: 'comorbidity', position: 2 },
  { id: 46, name: 'Área da assistência/tratamento', parent_group_id: 23, context: 'priority', position: 0 },
  { id: 47, name: 'Administrativo e outros setores', parent_group_id: 23, context: 'priority', position: 0 },
  { id: 48, name: 'Professor(a) em sala de aula', parent_group_id: 24, context: 'priority', position: 0, active: false },
  { id: 49, name: 'Administrativo e outros setores', parent_group_id: 24, context: 'priority', position: 0, active: false },
  { id: 50, name: 'Oficial em atividade de linha de frente', parent_group_id: 25, context: 'priority', position: 0, active: false },
  { id: 51, name: 'Oficial em atividade administrativa', parent_group_id: 25, context: 'priority', position: 0, active: false },
  { id: 52, name: 'Outra(s)', parent_group_id: 27, context: 'priority', position: 0, active: false },
  { id: 53, name: 'Pessoa com 60 anos ou mais', parent_group_id: nil, context: 'priority', position: 0, active: false },
  { id: 55, name: 'Estagiário da área da Saúde', parent_group_id: 23, context: 'priority', position: 0 },
  { id: 57, name: 'Atua em Hospital', parent_group_id: 23, context: 'priority', position: 0 },
  { id: 58, name: 'Pessoa com 90 anos ou mais', parent_group_id: nil, context: 'priority', position: 0, active: false },
  { id: 60, name: 'Trabalhadores do sistema funerário', parent_group_id: nil, context: 'priority', position: 13 },
  { id: 61, name: 'Trabalhador da Indústria em Geral', parent_group_id: nil, context: 'priority', position: 14 },
  { id: 62, name: 'Doença Pulmonar Obstrutiva Crônica', parent_group_id: 37, context: 'comorbidity', position: 0 },
  { id: 63, name: 'Fibrose Cística', parent_group_id: 37, context: 'comorbidity', position: 1 },
  { id: 64, name: 'Fibroses Pulmonares', parent_group_id: 37, context: 'comorbidity', position: 2 },
  { id: 65, name: 'Pneumoconioses', parent_group_id: 37, context: 'comorbidity', position: 3 },
  { id: 66, name: 'Displasia Broncopulmonar', parent_group_id: 37, context: 'comorbidity', position: 4 },
  { id: 67, name: 'Asma Grave (uso recorrente de corticoides sistêmicos, internação prévia por crise asmática)', parent_group_id: 37, context: 'comorbidity', position: 5 },
  { id: 68, name: 'Hipertensão Arterial Resistente (HAR)', parent_group_id: 38, context: 'comorbidity', position: 0, active: false },
  { id: 69, name: 'Hipertensão Arterial estágio 3', parent_group_id: 38, context: 'comorbidity', position: 1, active: false },
  { id: 70, name: 'Hipertensão Arterial estágios 1 e 2 com LOA e/ou comorbidade', parent_group_id: 38, context: 'comorbidity', position: 2, active: false },
  { id: 71, name: 'Insuficiência Cardíaca', parent_group_id: 39, context: 'comorbidity', position: 0 },
  { id: 72, name: 'Cor-pulmonale e Hipertensão Pulmonar', parent_group_id: 39, context: 'comorbidity', position: 1 },
  { id: 73, name: 'Cardiopatia Hipertensiva', parent_group_id: 39, context: 'comorbidity', position: 2 },
  { id: 74, name: 'Síndromes Coronarianas', parent_group_id: 39, context: 'comorbidity', position: 3 },
  { id: 75, name: 'Valvopatias', parent_group_id: 39, context: 'comorbidity', position: 4 },
  { id: 76, name: 'Miocardites e Pericardiopatias', parent_group_id: 39, context: 'comorbidity', position: 5 },
  { id: 77, name: 'Doenças da Aorta, dos grandes vasos e fístulas arteriovenosas', parent_group_id: 39, context: 'comorbidity', position: 6 },
  { id: 78, name: 'Arritmias Cardíacas', parent_group_id: 39, context: 'comorbidity', position: 7 },
  { id: 79, name: 'Cardiopatia Congênita no adulto', parent_group_id: 39, context: 'comorbidity', position: 8 },
  { id: 80, name: 'Próteses valvares e Dispositivos cardíacos implantados', parent_group_id: 39, context: 'comorbidity', position: 9 },
  { id: 81, name: 'Acidente Vascular Cerebral Isquêmico (AVC)', parent_group_id: 40, context: 'comorbidity', position: 0 },
  { id: 82, name: 'Acidente Vascular Cerebral Hemorrágico', parent_group_id: 40, context: 'comorbidity', position: 1 },
  { id: 83, name: 'Ataque Isquêmico Transitório', parent_group_id: 40, context: 'comorbidity', position: 2 },
  { id: 84, name: 'Demência Vascular', parent_group_id: 40, context: 'comorbidity', position: 3 },
  { id: 85, name: 'Doença renal crônica em terapia de substituição renal (diálise)', parent_group_id: 41, context: 'comorbidity', position: 0 },
  { id: 86, name: 'Em estágio 3 ou mais (taxa de filtração glomerular < 60ml/min/1,73 m2)', parent_group_id: 41, context: 'comorbidity', position: 1 },
  { id: 87, name: 'Síndrome Nefrótica', parent_group_id: 41, context: 'comorbidity', position: 2 },
  { id: 88, name: 'Transplantados de órgãos sólidos ou de medula óssea', parent_group_id: 42, context: 'comorbidity', position: 0, active: false },
  { id: 89, name: 'Pessoas vivendo com HIV e CD4 < 350 células/mm³', parent_group_id: 42, context: 'comorbidity', position: 1 },
  { id: 90, name: 'Doenças reumáticas imunomediadas sistêmicas em atividade e em uso de dose de prednisona equivalente >10mg/dia ou recebendo pulsoterapia com corticóide e/ou ciclofosfamida', parent_group_id: 42, context: 'comorbidity', position: 2, active: true },
  { id: 91, name: 'Demais indivíduos em uso de imunossupressores ou com imunodeficiências primárias', parent_group_id: 42, context: 'comorbidity', position: 3 },
  { id: 92, name: 'Gestantes e puérperas com comorbidades', parent_group_id: 1001, context: 'priority', position: 4 },
  { id: 93, name: 'Gestantes e puérperas sem comorbidades', parent_group_id: 1001, context: 'priority', position: 4 },
  { id: 94, name: 'Pessoas com deficiências permanentes cadastradas no Programa de Benefício de Prestação Continuada (BPC)', parent_group_id: nil, context: 'comorbidity', position: 5, active: false },
  { id: 95, name: 'Cirrose hepática - (Child-Pugh A, B ou C)', parent_group_id: nil, context: 'comorbidity', position: 11 },
  { id: 998, name: 'Não me encaixo em nenhum dos grupos listados', parent_group_id: nil, context: 'priority', position: 0 },
  { id: 999, name: 'Não possuo nenhuma das comorbidades ou a que tenho, não está na lista', parent_group_id: nil, context: 'comorbidity', position: 0 },
  { id: 1000, name: 'Transplantado de órgão sólido ou medula óssea', parent_group_id: nil, context: 'priority', position: 1 },
  { id: 1001, name: 'Gestantes e Puérperas (até 45 dias pós parto)', parent_group_id: nil, context: 'priority', position: 4 },
  { id: 1002, name: 'Recebe Benefício de Prestação Continuada (BPC)', parent_group_id: 35, context: 'priority', position: 1 },
  { id: 1003, name: 'Que não tem cadastro e não recebe Benefício de Prestação Continuada (BPC)', parent_group_id: 35, context: 'priority', position: 2 },
  { id: 1004, name: 'Pessoa com deficiência NÃO cadastrada no Benefício de Prestação Continuada (BPC)', parent_group_id: nil, context: 'priority', position: 4, active: false },
  { id: 1005, name: 'Hemoglobinopatias Graves', parent_group_id: nil, context: 'comorbidity', position: 20 },
  { id: 1006, name: 'Trabalhador (a) da Educação que atua no atendimento presencial em unidades escolares', parent_group_id: nil, context: 'priority', position: 3 },
  { id: 1007, name: 'Educação Infantil (professores e auxiliares) - Presencial', parent_group_id: 1006, context: 'priority', position: 0 },
  { id: 1008, name: 'Educação Especial - Presencial', parent_group_id: 1006, context: 'priority', position: 2 },
  { id: 1009, name: 'Equipe técnica, administrativa e pedagógica que atua em unidades escolares (gestão, limpeza, alimentação, orientadores de convivência) - Presencial', parent_group_id: 1006, context: 'priority', position: 0 },
  { id: 1010, name: 'Ensino Fundamental (professor, segundo professor, auxiliares, intérpretes de Libras) - Presencial', parent_group_id: 1006, context: 'priority', position: 0 },
  { id: 1011, name: 'Ensino Médio (professor, segundo professor, auxiliares, intérpretes de Libras) - Presencial', parent_group_id: 1006, context: 'priority', position: 0 },
  { id: 1012, name: 'Ensino Superior - Remoto', parent_group_id: 1015, context: 'priority', position: 0 },
  { id: 1013, name: 'Ensino Técnico', parent_group_id: 1006, context: 'priority', position: 0 },
  { id: 1014, name: 'Ensino de artes e cultura', parent_group_id: 1006, context: 'priority', position: 0 },
  { id: 1015, name: 'Trabalhador (a) da Educação que atua em atividade remota', parent_group_id: nil, context: 'priority', position: 2 },
  { id: 1016, name: 'Educação Infantil (professores e auxiliares) - Remoto', parent_group_id: 1015, context: 'priority', position: 0 },
  { id: 1017, name: 'Educação Especial - Remoto', parent_group_id: 1015, context: 'priority', position: 0 },
  { id: 1018, name: 'Equipe técnica, administrativa e pedagógica que atua em unidades escolares (gestão, limpeza, alimentação, orientadores de convivência) - Remoto', parent_group_id: 1015, context: 'priority', position: 0 },
  { id: 1019, name: 'Ensino Fundamental (professor, segundo professor, auxiliares, intérpretes de Libras) - Remoto', parent_group_id: 1015, context: 'priority', position: 0 },
  { id: 1020, name: 'Ensino Médio (professor, segundo professor, auxiliares, intérpretes de Libras) - Remoto', parent_group_id: 1015, context: 'priority', position: 0 },
  { id: 1021, name: 'Ensino Superior - Presencial', parent_group_id: 1006, context: 'priority', position: 0 },
  { id: 1022, name: 'Profissionais que atuam em atividade remota, EAD ou similares', parent_group_id: 1015, context: 'priority', position: 0 }
].each do |h|
  Group.find_or_initialize_by(id: h[:id]).tap do |group|
    group.attributes = { parent_group_id: nil, context: 'priority', active: true }.merge(h)
    group.save!
  end
end
